/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.zzih.rudder.ai.feedback;

import io.github.zzih.rudder.ai.dto.AiFeedbackDTO;
import io.github.zzih.rudder.common.utils.bean.BeanConvertUtils;
import io.github.zzih.rudder.dao.dao.AiFeedbackDao;
import io.github.zzih.rudder.dao.entity.AiFeedback;

import java.util.List;

import org.springframework.stereotype.Service;

import lombok.RequiredArgsConstructor;

/** 用户/系统反馈入口 —— assistant 消息的 👍/👎 + 执行结果自动打标。 */
@Service
@RequiredArgsConstructor
public class FeedbackService {

    private final AiFeedbackDao dao;

    public AiFeedback record(Long messageId, Long userId, String signal, String comment, boolean autoGenerated) {
        AiFeedback f = new AiFeedback();
        f.setMessageId(messageId);
        f.setUserId(userId);
        f.setSignal(signal);
        f.setComment(comment);
        f.setAutoGenerated(autoGenerated);
        dao.insert(f);
        return f;
    }

    public List<AiFeedback> listByMessage(Long messageId) {
        return dao.selectByMessage(messageId);
    }

    // ==================== Detail variants — controller 调,DTO 入出 ====================

    public AiFeedbackDTO recordDetail(Long messageId, Long userId, String signal, String comment,
                                      boolean autoGenerated) {
        return BeanConvertUtils.convert(record(messageId, userId, signal, comment, autoGenerated),
                AiFeedbackDTO.class);
    }

    public List<AiFeedbackDTO> listByMessageDetail(Long messageId) {
        return BeanConvertUtils.convertList(listByMessage(messageId), AiFeedbackDTO.class);
    }
}
